language: generic

cache:
  directories:
    # General SwiftPM
    - .build
    # XCodebuild cache
    - Build

matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - export PATH=$HOME/.local/bin:$PATH
        - pip install --user proselint
        - npm install -g danger
      script:
        - proselint -j README.md 
        - swift test
        - DEBUG="*" swift run danger-swift ci
    - os: linux
      sudo: required
      dist: trusty
      install:
        - pip install --user proselint
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
        - npm install -g danger
      script:
        - ls -la
        - swift test
        - DEBUG="*" swift run danger-swift ci
        - ls -la
