language: generic

cache:
  directories:
    # General SwiftPM
    - .build
    # XCodebuild cache
    - Build

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      install:
        - export PATH=$HOME/Library/Python/2.7/bin:$PATH
        - npm install -g danger
      script:
        - swift test
        - DEBUG="*" swift run danger-swift ci
    - os: linux
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1
        - npm install -g danger
      script:
        - ls -la
        - swift test
        - DEBUG="*" swift run danger-swift ci
        - ls -la
